### ISSUE TITLE
flask needed

### ISSUE THREAD

**Issue by Sa3oobe** [udacity/fullstack-nanodegree-vm#118]
i am trying to run forum.py file in both the VM and localy but it shows the following error:

 File "forum.py", line 5, in <module>
    from flask import Flask, request, redirect, url_for
ImportError: No module named flask

should i install flask, and how i can do that?

**Comment by anantakrroy** [comment]
To install Flask follow instructions here - https://flask.palletsprojects.com/en/1.1.x/installation/#install-flask @Sa3oobe

**Comment by Sa3oobe** [comment]
> 
> 
> To install Flask follow instructions here - https://flask.palletsprojects.com/en/1.1.x/installation/#install-flask @Sa3oobe

Thanks for the replay man :)

**Comment by nfuste** [comment]
Hi!

I have the same problem, but when I try $ pip install Flask, I get the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**Comment by ant1fact** [comment]
Having the same issue.. Added some blank lines between terminal inputs to make it easier to read. Please provide a solution

`vagrant@vagrant:/vagrant/forum$ python forum.py
Traceback (most recent call last):
  File "forum.py", line 5, in <module>
    from flask import Flask, request, redirect, url_for
ImportError: No module named flask


vagrant@vagrant:/vagrant/forum$ pip install Flask
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax


vagrant@vagrant:/vagrant/forum$ python -m pip install Flask
Collecting Flask
  Downloading https://files.pythonhosted.org/packages/95/40/b976286b5e7ba01794a7e7588e7e7fa27fb16c6168fa849234840bf0f61d/Flask-2.0.2.tar.gz (628kB)
    100% |████████████████████████████████| 634kB 2.1MB/s
Collecting Werkzeug>=2.0 (from Flask)
  Downloading https://files.pythonhosted.org/packages/83/3c/ecdb36f49ab06defb0d5a466cfeb4ae90a55d02cfef379f781da2801a45d/Werkzeug-2.0.2.tar.gz (895kB)
    100% |████████████████████████████████| 901kB 1.1MB/s
  Requested Werkzeug>=2.0 from https://files.pythonhosted.org/packages/83/3c/ecdb36f49ab06defb0d5a466cfeb4ae90a55d02cfef379f781da2801a45d/Werkzeug-2.0.2.tar.gz#sha256=aa2bb6fc8dee8d6c504c0ac1e7f5f7dc5810a9903e793b6f715a9f015bdadb9a (from Flask), but installing version 0.0.0
Collecting Jinja2>=3.0 (from Flask)
  Downloading https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423efa6c6/Jinja2-3.0.3.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 3.8MB/s
  Requested Jinja2>=3.0 from https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423efa6c6/Jinja2-3.0.3.tar.gz#sha256=611bb273cd68f3b993fabdc4064fc858c5b47a973cb5aa7999ec1ba405c87cd7 (from Flask), but installing version 0.0.0
Collecting itsdangerous>=2.0 (from Flask)
  Downloading https://files.pythonhosted.org/packages/58/66/d6c5859dcac92b442626427a8c7a42322068c5cd5d4a463ce78b93f730b7/itsdangerous-2.0.1.tar.gz (59kB)
    100% |████████████████████████████████| 61kB 7.7MB/s
  Requested itsdangerous>=2.0 from https://files.pythonhosted.org/packages/58/66/d6c5859dcac92b442626427a8c7a42322068c5cd5d4a463ce78b93f730b7/itsdangerous-2.0.1.tar.gz#sha256=9e724d68fc22902a1435351f84c3fb8623f303fffcc566a4cb952df8c572cff0 (from Flask), but installing version 0.0.0
Collecting click>=7.1.2 (from Flask)
  Downloading https://files.pythonhosted.org/packages/f4/09/ad003f1e3428017d1c3da4ccc9547591703ffea548626f47ec74509c5824/click-8.0.3.tar.gz (329kB)
    100% |████████████████████████████████| 337kB 3.3MB/s
  Requested click>=7.1.2 from https://files.pythonhosted.org/packages/f4/09/ad003f1e3428017d1c3da4ccc9547591703ffea548626f47ec74509c5824/click-8.0.3.tar.gz#sha256=410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b (from Flask), but installing version 0.0.0
Collecting dataclasses; python_version < "3.7" (from Werkzeug>=2.0->Flask)
  Downloading https://files.pythonhosted.org/packages/1f/12/7919c5d8b9c497f9180db15ea8ead6499812ea8264a6ae18766d93c59fe5/dataclasses-0.8.tar.gz
Collecting MarkupSafe>=2.0 (from Jinja2>=3.0->Flask)
  Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
  Requested MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz#sha256=594c67807fb16238b30c44bdf74f36c02cdf22d1c8cda91ef8a0ed8dabf5620a (from Jinja2>=3.0->Flask), but installing version 0.0.0
Collecting colorama; platform_system == "Windows" (from click>=7.1.2->Flask)
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from click>=7.1.2->Flask)
  Downloading https://files.pythonhosted.org/packages/2e/6d/4508b1922b1610f6646fd95681fa1b0c092df35ec14018218f4638b7342a/importlib_metadata-4.8.2.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 8.1MB/s
  Running setup.py (path:/tmp/pip-build-l3rikO/importlib-metadata/setup.py) egg_info for package importlib-metadata produced metadata for project name unknown. Fix your #egg=importlib-metadata fragments.
Building wheels for collected packages: Flask, Werkzeug, Jinja2, itsdangerous, click, dataclasses, MarkupSafe, unknown, unknown
  Running setup.py bdist_wheel for Flask ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/a5/29/97/4be96033477464a016fff546b5496b7ffae321bbec47132aad
  Running setup.py bdist_wheel for Werkzeug ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/c0/8d/cd/c03717cb4b5ef862f87062613f47b5e06490314720ee323a93
  Running setup.py bdist_wheel for Jinja2 ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/7b/76/54/3836433d16606402dc650c321fffbc189d95385143cef5b937
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/50/11/ab/8a6c7f9176da2b9215a6c51f294ea47bb0796769d172cd3224
  Running setup.py bdist_wheel for click ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/06/99/9b/c7bcc138786c3b0977bc4638bc9a1ab9feb04483b97e7c6b3d
  Running setup.py bdist_wheel for dataclasses ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/8b/a6/80/e864b275adcd9fc4e6e7f3b9b7f72c4c87f71cf3da79188e56
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/21/8d/8d/03713c46963ee240d5105dd963d75b655461e13c95332962c4
  Running setup.py bdist_wheel for unknown ... done
  Stored in directory: /home/vagrant/.cache/pip/wheels/f3/cb/0c/1ec67821197ee357a9b142d69df3a2668c89618122c28ce449
  Running setup.py bdist_wheel for unknown ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l3rikO/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp78eIbdpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-l3rikO/unknown/setup.py'

  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l3rikO/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-build-l3rikO/unknown/setup.py'

  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built Flask Werkzeug Jinja2 itsdangerous click dataclasses MarkupSafe unknown
Failed to build unknown
Installing collected packages: dataclasses, Werkzeug, MarkupSafe, Jinja2, itsdangerous, colorama, unknown, click, Flask
Successfully installed Flask-0.0.0 Jinja2-0.0.0 MarkupSafe-0.0.0 Werkzeug-0.0.0 click-0.0.0 colorama-0.4.4 dataclasses-0.8 itsdangerous-0.0.0 unknown-0.0.0
You are using pip version 8.1.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


vagrant@vagrant:/vagrant/forum$ python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/da/f6/c83229dcc3635cdeb51874184241a9508ada15d8baa337a41093fab58011/pip-21.3.1.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 807kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zEBnai/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zEBnai/pip/
You are using pip version 8.1.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

**Comment by anantakrroy** [comment]
> Having the same issue.. Added some blank lines between terminal inputs to make it easier to read. Please provide a solution
> 
> ```
> vagrant@vagrant:/vagrant/forum$ python forum.py
> Traceback (most recent call last):
>   File "forum.py", line 5, in <module>
>     from flask import Flask, request, redirect, url_for
> ImportError: No module named flask
> 
> 
> vagrant@vagrant:/vagrant/forum$ pip install Flask
> Traceback (most recent call last):
>   File "/usr/local/bin/pip", line 7, in <module>
>     from pip._internal.cli.main import main
>   File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
>     sys.stderr.write(f"ERROR: {exc}")
>                                    ^
> SyntaxError: invalid syntax
> 
> 
> vagrant@vagrant:/vagrant/forum$ python -m pip install Flask
> Collecting Flask
>   Downloading https://files.pythonhosted.org/packages/95/40/b976286b5e7ba01794a7e7588e7e7fa27fb16c6168fa849234840bf0f61d/Flask-2.0.2.tar.gz (628kB)
>     100% |████████████████████████████████| 634kB 2.1MB/s
> Collecting Werkzeug>=2.0 (from Flask)
>   Downloading https://files.pythonhosted.org/packages/83/3c/ecdb36f49ab06defb0d5a466cfeb4ae90a55d02cfef379f781da2801a45d/Werkzeug-2.0.2.tar.gz (895kB)
>     100% |████████████████████████████████| 901kB 1.1MB/s
>   Requested Werkzeug>=2.0 from https://files.pythonhosted.org/packages/83/3c/ecdb36f49ab06defb0d5a466cfeb4ae90a55d02cfef379f781da2801a45d/Werkzeug-2.0.2.tar.gz#sha256=aa2bb6fc8dee8d6c504c0ac1e7f5f7dc5810a9903e793b6f715a9f015bdadb9a (from Flask), but installing version 0.0.0
> Collecting Jinja2>=3.0 (from Flask)
>   Downloading https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423efa6c6/Jinja2-3.0.3.tar.gz (269kB)
>     100% |████████████████████████████████| 276kB 3.8MB/s
>   Requested Jinja2>=3.0 from https://files.pythonhosted.org/packages/91/a5/429efc6246119e1e3fbf562c00187d04e83e54619249eb732bb423efa6c6/Jinja2-3.0.3.tar.gz#sha256=611bb273cd68f3b993fabdc4064fc858c5b47a973cb5aa7999ec1ba405c87cd7 (from Flask), but installing version 0.0.0
> Collecting itsdangerous>=2.0 (from Flask)
>   Downloading https://files.pythonhosted.org/packages/58/66/d6c5859dcac92b442626427a8c7a42322068c5cd5d4a463ce78b93f730b7/itsdangerous-2.0.1.tar.gz (59kB)
>     100% |████████████████████████████████| 61kB 7.7MB/s
>   Requested itsdangerous>=2.0 from https://files.pythonhosted.org/packages/58/66/d6c5859dcac92b442626427a8c7a42322068c5cd5d4a463ce78b93f730b7/itsdangerous-2.0.1.tar.gz#sha256=9e724d68fc22902a1435351f84c3fb8623f303fffcc566a4cb952df8c572cff0 (from Flask), but installing version 0.0.0
> Collecting click>=7.1.2 (from Flask)
>   Downloading https://files.pythonhosted.org/packages/f4/09/ad003f1e3428017d1c3da4ccc9547591703ffea548626f47ec74509c5824/click-8.0.3.tar.gz (329kB)
>     100% |████████████████████████████████| 337kB 3.3MB/s
>   Requested click>=7.1.2 from https://files.pythonhosted.org/packages/f4/09/ad003f1e3428017d1c3da4ccc9547591703ffea548626f47ec74509c5824/click-8.0.3.tar.gz#sha256=410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b (from Flask), but installing version 0.0.0
> Collecting dataclasses; python_version < "3.7" (from Werkzeug>=2.0->Flask)
>   Downloading https://files.pythonhosted.org/packages/1f/12/7919c5d8b9c497f9180db15ea8ead6499812ea8264a6ae18766d93c59fe5/dataclasses-0.8.tar.gz
> Collecting MarkupSafe>=2.0 (from Jinja2>=3.0->Flask)
>   Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
>   Requested MarkupSafe>=2.0 from https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz#sha256=594c67807fb16238b30c44bdf74f36c02cdf22d1c8cda91ef8a0ed8dabf5620a (from Jinja2>=3.0->Flask), but installing version 0.0.0
> Collecting colorama; platform_system == "Windows" (from click>=7.1.2->Flask)
>   Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
> Collecting importlib-metadata; python_version < "3.8" (from click>=7.1.2->Flask)
>   Downloading https://files.pythonhosted.org/packages/2e/6d/4508b1922b1610f6646fd95681fa1b0c092df35ec14018218f4638b7342a/importlib_metadata-4.8.2.tar.gz (41kB)
>     100% |████████████████████████████████| 51kB 8.1MB/s
>   Running setup.py (path:/tmp/pip-build-l3rikO/importlib-metadata/setup.py) egg_info for package importlib-metadata produced metadata for project name unknown. Fix your #egg=importlib-metadata fragments.
> Building wheels for collected packages: Flask, Werkzeug, Jinja2, itsdangerous, click, dataclasses, MarkupSafe, unknown, unknown
>   Running setup.py bdist_wheel for Flask ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/a5/29/97/4be96033477464a016fff546b5496b7ffae321bbec47132aad
>   Running setup.py bdist_wheel for Werkzeug ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/c0/8d/cd/c03717cb4b5ef862f87062613f47b5e06490314720ee323a93
>   Running setup.py bdist_wheel for Jinja2 ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/7b/76/54/3836433d16606402dc650c321fffbc189d95385143cef5b937
>   Running setup.py bdist_wheel for itsdangerous ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/50/11/ab/8a6c7f9176da2b9215a6c51f294ea47bb0796769d172cd3224
>   Running setup.py bdist_wheel for click ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/06/99/9b/c7bcc138786c3b0977bc4638bc9a1ab9feb04483b97e7c6b3d
>   Running setup.py bdist_wheel for dataclasses ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/8b/a6/80/e864b275adcd9fc4e6e7f3b9b7f72c4c87f71cf3da79188e56
>   Running setup.py bdist_wheel for MarkupSafe ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/21/8d/8d/03713c46963ee240d5105dd963d75b655461e13c95332962c4
>   Running setup.py bdist_wheel for unknown ... done
>   Stored in directory: /home/vagrant/.cache/pip/wheels/f3/cb/0c/1ec67821197ee357a9b142d69df3a2668c89618122c28ce449
>   Running setup.py bdist_wheel for unknown ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l3rikO/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp78eIbdpip-wheel- --python-tag cp27:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>   IOError: [Errno 2] No such file or directory: '/tmp/pip-build-l3rikO/unknown/setup.py'
> 
>   ----------------------------------------
>   Failed building wheel for unknown
>   Running setup.py clean for unknown
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-l3rikO/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>   IOError: [Errno 2] No such file or directory: '/tmp/pip-build-l3rikO/unknown/setup.py'
> 
>   ----------------------------------------
>   Failed cleaning build dir for unknown
> Successfully built Flask Werkzeug Jinja2 itsdangerous click dataclasses MarkupSafe unknown
> Failed to build unknown
> Installing collected packages: dataclasses, Werkzeug, MarkupSafe, Jinja2, itsdangerous, colorama, unknown, click, Flask
> Successfully installed Flask-0.0.0 Jinja2-0.0.0 MarkupSafe-0.0.0 Werkzeug-0.0.0 click-0.0.0 colorama-0.4.4 dataclasses-0.8 itsdangerous-0.0.0 unknown-0.0.0
> You are using pip version 8.1.1, however version 21.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 
> 
> vagrant@vagrant:/vagrant/forum$ python -m pip install --upgrade pip
> Collecting pip
>   Downloading https://files.pythonhosted.org/packages/da/f6/c83229dcc3635cdeb51874184241a9508ada15d8baa337a41093fab58011/pip-21.3.1.tar.gz (1.7MB)
>     100% |████████████████████████████████| 1.7MB 807kB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-zEBnai/pip/setup.py", line 7
>         def read(rel_path: str) -> str:
>                          ^
>     SyntaxError: invalid syntax
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zEBnai/pip/
> You are using pip version 8.1.1, however version 21.3.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ```

@ant1fact Did you have a chance to look at this related and popular [Stackoverflow question](https://stackoverflow.com/questions/65896334/python-pip-broken-with-sys-stderr-writeferror-exc)?

**Comment by ant1fact** [comment]
@anantakrroy Thanks for the tip but no amount of package massaging resulted in having a working flask installation. This is very frustrating as I have paid for the fullstack nanodegree program. I kindly ask the maintainers of this repo to apply the fix themselves as others seem to have the same issue as well.

**Comment by ant1fact** [comment]
In the meantime I will be using Ubuntu 18.04 on WSL2. I have been working with the course files with this setup for a few hours and so far no issues. I think Ubuntu 16.04 should be deprecated for the nanodegree as the LTS window ended on April 30th 2021. The other issue I had with the VirtualBox + Vagrant setup is that the version of VirtualBox required by the installation instructions is no longer possible to install on Windows 11. I know Windows 11 is still fairly new but it should be taken into consideration.

Kind regards,
David

**Comment by SudKul** [comment]
Hi everyone, 
Has anyone tried the fix suggested in https://github.com/udacity/fullstack-nanodegree-vm/pull/128 to update the box version?

**Comment by SudKul** [comment]
Merged https://github.com/udacity/fullstack-nanodegree-vm/pull/128
