### ISSUE TITLE
vagrant up fails - ‘replace’: can’t modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by miranda-elliott** [udacity/fullstack-nanodegree-vm#90]
I have Vagrant 2.0.3 and VirtualBox 5.2.8 installed. I cloned my fork of the fullstack-nanodegree-vm github project into a directory named fullstack. When I try to run vagrant up in fullstack/vagrant I get the following error:

```
.../fullstack/vagrant/Vagrantfile:5:in `replace': can't modify frozen String (RuntimeError)
	from .../fullstack/vagrant/Vagrantfile:5:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:771:in `new'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:771:in `vagrantfile'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:517:in `host'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:185:in `block in action_runner'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:504:in `hook'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:753:in `unload'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `<main>'
```

Has anyone else experienced this? How do I fix it?

**Comment by miranda-elliott** [comment]
Found someone else having the same issue: https://discussions.udacity.com/t/vagrant-up-error-cant-modify-frozen-string-runtimeerror/635592. Downloaded Vagrant 2.0.1 per that thread's answers and the error is resolved. You should make a note in the README that Vagrant 2.0.3 isn't compatible with this project.
